name: fewa_module_suite
description: "A new Flutter project."
resolution: workspace

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  foundation:
    path: ../../packages/foundation
  todo:
    path: ../../modules/todo

 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
